import { getDisplayText } from './formatting';
import { getPrimaryIdentifierValue } from './csl-utils';
import { sortCitations } from './sorter';

export const CSL_JSON_EXPORT_FILENAME = 'bibliography.csl.json';
export const CSL_JSON_EXPORT_MIME_TYPE =
	'application/vnd.citationstyles.csl+json;charset=utf-8';
export const BIBTEX_EXPORT_FILENAME = 'bibliography.bib';
export const BIBTEX_EXPORT_MIME_TYPE = 'text/x-bibtex;charset=utf-8';
export const BIBLATEX_EXPORT_FILENAME = 'bibliography.biblatex.bib';
export const BIBLATEX_EXPORT_MIME_TYPE = 'text/x-bibtex;charset=utf-8';
export const RIS_EXPORT_FILENAME = 'bibliography.ris';
export const RIS_EXPORT_MIME_TYPE =
	'application/x-research-info-systems;charset=utf-8';

async function getCiteConstructor() {
	const [{ Cite }] = await Promise.all([
		import('@citation-js/core'),
		import('@citation-js/plugin-bibtex'),
	]);

	return Cite;
}

/**
 * Normalize citation-js' TeX quote ligatures to UTF-8 punctuation for BibTeX
 * exports. Modern Zotero and Mendeley imports preserve UTF-8 quotes, but may
 * import TeX opening quotes (``) as literal backticks.
 *
 * @param {string} bibtex BibTeX content generated by citation-js.
 * @return {string} BibTeX content with Unicode quote characters.
 *
 * @since 1.0.0
 */
export function normalizeBibtexUnicodeQuotes(bibtex) {
	return bibtex
		.replace(/\\textquotedblleft\{\}/gu, '“')
		.replace(/\\textquotedblright\{\}/gu, '”')
		.replace(/\\textquoteleft\{\}/gu, '‘')
		.replace(/\\textquoteright\{\}/gu, '’')
		.replace(/``/gu, '“')
		.replace(/''/gu, '”');
}

const RIS_TYPE_MAP = {
	'article-journal': 'JOUR',
	'article-magazine': 'MGZN',
	'article-newspaper': 'NEWS',
	book: 'BOOK',
	chapter: 'CHAP',
	collection: 'BOOK',
	thesis: 'THES',
	report: 'RPRT',
	'paper-conference': 'CONF',
	webpage: 'ELEC',
	review: 'GEN',
	'review-book': 'GEN',
};

function getRisType(csl) {
	return RIS_TYPE_MAP[csl.type] || 'GEN';
}

function appendRisLine(lines, tag, value) {
	if (value === undefined || value === null || value === '') {
		return;
	}

	lines.push(`${tag}  - ${value}`);
}

/**
 * Get a publication year for output fields. Missing dates intentionally
 * return undefined so RIS date tags are omitted instead of sorted last.
 *
 * @param {Object} csl CSL-JSON object.
 * @return {number|undefined} Publication year for export output.
 */
function getIssuedYearForExport(csl) {
	return csl.issued?.['date-parts']?.[0]?.[0];
}

function splitPageRange(page = '') {
	const [start, end] = String(page).split(/\s*[-–—]\s*/u);

	return {
		start: start || '',
		end: end || '',
	};
}

function formatRisAuthor(author) {
	if (author.literal) {
		return author.literal;
	}

	if (author.family && author.given) {
		return `${author.family}, ${author.given}`;
	}

	return author.family || author.given || '';
}

// Note: this intentionally restricts to ASCII word characters, so non-Latin
// scripts (e.g. CJK) and some letters (e.g. "ø") that NFKD does not decompose
// are dropped. Such citations fall through to the title slug, then to the
// generic "citation" basename. This keeps download filenames filesystem-safe
// across platforms at the cost of less specific names for those entries.
function slugifyExportName(value) {
	return String(value || '')
		.normalize('NFKD')
		.replace(/[^\w\s-]/g, '')
		.trim()
		.replace(/[\s_]+/g, '-')
		.replace(/-{2,}/g, '-')
		.replace(/^-+|-+$/g, '')
		.slice(0, 60);
}

/**
 * Build a short, human-meaningful, filesystem-safe basename for per-entry
 * export download filenames (e.g. "watson1953", "Kuhn-1962"). Prefers the
 * BibTeX citation-key, then first-author + year, then a title slug, then a
 * generic "citation" fallback. Used by save() instead of the internal UUID id.
 *
 * @param {Object} csl CSL-JSON object for a single citation.
 * @return {string} Slugged basename (no extension).
 */
export function getCitationExportBasename(csl) {
	if (!csl) {
		return 'citation';
	}

	const citationKey =
		typeof csl['citation-key'] === 'string' ? csl['citation-key'] : '';
	const fromKey = slugifyExportName(citationKey);
	if (fromKey) {
		return fromKey;
	}

	const firstAuthor = (csl.author || [])[0] || {};
	const namePart =
		firstAuthor.family || firstAuthor.literal || firstAuthor.given || '';
	const year = csl.issued?.['date-parts']?.[0]?.[0] || '';
	const fromAuthorYear = slugifyExportName(
		[namePart, year].filter(Boolean).join('-')
	);
	if (fromAuthorYear) {
		return fromAuthorYear;
	}

	const fromTitle = slugifyExportName(
		String(csl.title || '')
			.split(/\s+/)
			.slice(0, 4)
			.join(' ')
	);
	return fromTitle || 'citation';
}

export function cslToRisEntry(csl) {
	const lines = [];
	const { start, end } = splitPageRange(csl.page);

	appendRisLine(lines, 'TY', getRisType(csl));

	for (const author of csl.author || []) {
		appendRisLine(lines, 'AU', formatRisAuthor(author));
	}

	for (const editor of csl.editor || []) {
		appendRisLine(lines, 'A2', formatRisAuthor(editor));
	}

	appendRisLine(lines, 'TI', csl.title);
	appendRisLine(
		lines,
		csl.type === 'book' ? 'BT' : 'T2',
		csl['container-title']
	);
	appendRisLine(lines, 'PB', csl.publisher);
	appendRisLine(lines, 'PY', getIssuedYearForExport(csl));
	appendRisLine(lines, 'DA', getIssuedYearForExport(csl));
	appendRisLine(lines, 'VL', csl.volume);
	appendRisLine(lines, 'IS', csl.issue);
	appendRisLine(lines, 'SP', start);
	appendRisLine(lines, 'EP', end);
	appendRisLine(lines, 'DO', csl.DOI);
	appendRisLine(lines, 'UR', csl.URL);
	appendRisLine(lines, 'LA', csl.language);
	appendRisLine(
		lines,
		'SN',
		getPrimaryIdentifierValue(csl.ISBN) ||
			getPrimaryIdentifierValue(csl.ISSN)
	);

	lines.push('ER  - ');

	return lines.join('\n');
}

/**
 * Build plain-text bibliography content.
 *
 * @param {Array}  citations     Array of citation objects.
 * @param {string} citationStyle Citation style key.
 * @return {string} Plain-text bibliography.
 *
 * @since 0.1.0
 */
export function buildPlainTextBibliographyContent(citations, citationStyle) {
	const sortedCitations = sortCitations(citations, citationStyle);

	return `${sortedCitations
		.map((citation) => getDisplayText(citation))
		.join('\n')}\n`;
}

/**
 * Build CSL-JSON export content.
 *
 * @param {Array}  citations     Array of citation objects.
 * @param {string} citationStyle Citation style key.
 * @return {string} JSON string of CSL-JSON array.
 *
 * @since 0.1.0
 */
export function buildCslJsonExportContent(citations, citationStyle) {
	const sortedCitations = sortCitations(citations, citationStyle);
	const cslArray = sortedCitations.map((citation) => citation.csl);

	return `${JSON.stringify(cslArray, null, 2)}\n`;
}

export function downloadTextExport(
	{ content, filename, mimeType },
	{ documentRef = document, urlRef = URL, BlobCtor = Blob } = {}
) {
	if (
		!documentRef?.createElement ||
		!documentRef?.body ||
		!urlRef?.createObjectURL ||
		!BlobCtor
	) {
		throw new Error('Download API unavailable');
	}

	const fileBlob = new BlobCtor([content], {
		type: mimeType,
	});
	const downloadUrl = urlRef.createObjectURL(fileBlob);
	const link = documentRef.createElement('a');

	link.href = downloadUrl;
	link.download = filename;
	link.rel = 'noopener';
	documentRef.body.appendChild(link);
	link.click();
	link.remove();
	urlRef.revokeObjectURL?.(downloadUrl);

	return undefined;
}

/**
 * Trigger download of CSL-JSON export file.
 *
 * @param {Array}  citations      Array of citation objects.
 * @param {string} citationStyle  Citation style key.
 * @param {Object} [dependencies] Test injection for dependencies.
 * @return {void}
 *
 * @since 0.1.0
 */
export function downloadCslJsonExport(citations, citationStyle, dependencies) {
	return downloadTextExport(
		{
			content: buildCslJsonExportContent(citations, citationStyle),
			filename: CSL_JSON_EXPORT_FILENAME,
			mimeType: CSL_JSON_EXPORT_MIME_TYPE,
		},
		dependencies
	);
}

/**
 * Build BibTeX export content.
 *
 * @param {Array}  citations          Array of citation objects.
 * @param {string} citationStyle      Citation style key.
 * @param {Object} [options]          Options.
 * @param {Object} [options.CiteCtor] Test injection for Cite constructor.
 * @return {Promise<string>} BibTeX formatted string.
 *
 * @since 0.1.0
 */
export async function buildBibtexExportContent(
	citations,
	citationStyle,
	{ CiteCtor } = {}
) {
	const sortedCitations = sortCitations(citations, citationStyle);
	const cslArray = sortedCitations.map((citation) => citation.csl);
	const CiteClass = CiteCtor || (await getCiteConstructor());
	const cite = new CiteClass(cslArray);

	return `${normalizeBibtexUnicodeQuotes(cite.format('bibtex'))}\n`;
}

/**
 * Trigger download of BibTeX export file.
 *
 * @param {Array}  citations      Array of citation objects.
 * @param {string} citationStyle  Citation style key.
 * @param {Object} [dependencies] Test injection for dependencies.
 * @return {Promise<void>}
 *
 * @since 0.1.0
 */
export async function downloadBibtexExport(
	citations,
	citationStyle,
	dependencies
) {
	const { CiteCtor, ...downloadDependencies } = dependencies || {};

	return downloadTextExport(
		{
			content: await buildBibtexExportContent(citations, citationStyle, {
				CiteCtor,
			}),
			filename: BIBTEX_EXPORT_FILENAME,
			mimeType: BIBTEX_EXPORT_MIME_TYPE,
		},
		downloadDependencies
	);
}

/**
 * Build BibLaTeX export content.
 *
 * BibLaTeX uses richer field semantics than legacy BibTeX: `date` instead of
 * `year`, `journaltitle` instead of `journal`, and full Unicode support without
 * TeX ligatures. The same @citation-js/plugin-bibtex package provides the
 * `biblatex` format string.
 *
 * @param {Array}  citations          Array of citation objects.
 * @param {string} citationStyle      Citation style key.
 * @param {Object} [options]          Options.
 * @param {Object} [options.CiteCtor] Test injection for Cite constructor.
 * @return {Promise<string>} BibLaTeX formatted string.
 *
 * @since 1.2.0
 */
export async function buildBiblatexExportContent(
	citations,
	citationStyle,
	{ CiteCtor } = {}
) {
	const sortedCitations = sortCitations(citations, citationStyle);
	const cslArray = sortedCitations.map((citation) => citation.csl);
	const CiteClass = CiteCtor || (await getCiteConstructor());
	const cite = new CiteClass(cslArray);

	return `${cite.format('biblatex')}\n`;
}

/**
 * Trigger download of BibLaTeX export file.
 *
 * @param {Array}  citations      Array of citation objects.
 * @param {string} citationStyle  Citation style key.
 * @param {Object} [dependencies] Test injection for dependencies.
 * @return {Promise<void>}
 *
 * @since 1.2.0
 */
export async function downloadBiblatexExport(
	citations,
	citationStyle,
	dependencies
) {
	const { CiteCtor, ...downloadDependencies } = dependencies || {};

	return downloadTextExport(
		{
			content: await buildBiblatexExportContent(
				citations,
				citationStyle,
				{
					CiteCtor,
				}
			),
			filename: BIBLATEX_EXPORT_FILENAME,
			mimeType: BIBLATEX_EXPORT_MIME_TYPE,
		},
		downloadDependencies
	);
}

/**
 * Build RIS export content.
 *
 * @param {Array}  citations     Array of citation objects.
 * @param {string} citationStyle Citation style key.
 * @return {string} RIS formatted string.
 *
 * @since 0.1.0
 */
export function buildRisExportContent(citations, citationStyle) {
	const sortedCitations = sortCitations(citations, citationStyle);
	const cslArray = sortedCitations.map((citation) => citation.csl);

	return `${cslArray.map(cslToRisEntry).join('\n\n')}\n`;
}

/**
 * Trigger download of RIS export file.
 *
 * @param {Array}  citations      Array of citation objects.
 * @param {string} citationStyle  Citation style key.
 * @param {Object} [dependencies] Test injection for dependencies.
 * @return {void}
 *
 * @since 0.1.0
 */
export function downloadRisExport(citations, citationStyle, dependencies) {
	return downloadTextExport(
		{
			content: buildRisExportContent(citations, citationStyle),
			filename: RIS_EXPORT_FILENAME,
			mimeType: RIS_EXPORT_MIME_TYPE,
		},
		dependencies
	);
}
